on:
  push:
    branches:
      '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Monte-Carlo Pi Evaluation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the code
        run: |
          apt-get install -y cmake g++ mpich

      - name: Build the code
        run: |
          mkdir build
          cd build
          cmake --build .

      - name: Run the code
        run: |
          pwd

